services:
  postgres:
    image: postgres:latest
    container_name: my_postgresnew
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabasenew
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  book-api:
    build:
      context: .
    container_name: book-api-container
    environment:
      DB_HOST: postgres
      DB_NAME: mydatabasenew
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:


